# Generated by Django 3.0.8 on 2021-06-14 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210613_0105"),
        ("nora", "0002_auto_20210612_0257"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("customization", models.TextField()),
                ("place_order", models.BooleanField(default=False)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nora.Menu"
                    ),
                ),
                (
                    "plate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nora.Plate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.Client",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "menu")},
            },
        ),
    ]
