# Generated by Django 3.0.8 on 2021-06-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210613_0105"),
        ("nora", "0003_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="client",
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("client", "menu")},
        ),
    ]
