# Generated by Django 3.0.8 on 2021-06-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nora", "0004_auto_20210614_0415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(
                auto_created=True, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
