# Generated by Django 3.0.8 on 2021-06-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nora", "0006_auto_20210614_0528"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="plate",
            new_name="plates",
        ),
    ]
