# Generated by Django 3.0.8 on 2021-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nora", "0007_auto_20210615_0435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customization",
            field=models.TextField(blank=True, null=True),
        ),
    ]
