# Generated by Django 3.0.8 on 2021-06-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("country_code", models.TextField(max_length=2)),
                ("slack_id", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
